/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("gestalt.java-library-conventions")
    id("gestalt.java-test-conventions")
    id("gestalt.java-code-quality-conventions")
}

dependencies {

}
