/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

dependencies {
    implementation(libs.gradle.ben.manes.versions)
    implementation(libs.gradle.git.versions)
    implementation(libs.gradle.error.prone)

    implementation(libs.gradle.kotlin)
    implementation(libs.gradle.dokka)
    implementation(libs.gradle.detekt)
    implementation(files(libs.javaClass.superclass.protectionDomain.codeSource.location))
}


